version: '3.9'

services:
  api:
    build:
      context: ./src/Produtos
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=produtosdb;User=root;Password=yourpassword;
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 010203
      MYSQL_DATABASE: ProdutosDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./src/ProdutosMFront
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

      
volumes:
  mysql_data:
